name: Upload Data to BigQuery

on:
  schedule:
    - cron: "0 */12 * * *" # Run every 12 hours
    #- cron: "0 12 * * *"  # Run every day at noon EST
  push:
    branches:
      - main

jobs:
  upload_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade google-cloud-bigquery
          pip install requests

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.2.2
        with:
          name: "credentials.json"
          json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Upload data to BigQuery
        run: python uploadData.py

      - name: Cleanup
        run: rm credentials.json

