name: Upload Data to BigQuery

on:
  schedule:
    - cron: "0 */12 * * *" # Run every 12 hours
    #- cron: "0 12 * * *"  # Run every day at noon EST
  push:
    branches:
      - main

jobs:
  upload_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade google-cloud-bigquery
          pip install requests

      - name: Set Google Cloud credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > key.json
          python uploadData.py
      
      - name: Clean up
        run: |
          rm -f key.json

